### PR TITLE
Don't proxy special methods to model in ProxyModel.__getattr__

### LINKED ISSUE #107: DRF breakage
I'm just going through an exercise of upgrading an internal app with very old versions to slightly less old and ran into some breakage relating to #88 which I think requires a code change here.

```python
class NotificationGroupSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.NotificationGroup
        exclude = ()

    members = GM2MSerializerField(queryset=autocomplete.QuerySetSequence(User.objects.all(), Group.objects.all()))
```

This worked fine in django 2.2 and drf 3.9. Having bumped upto django 3.2 and drf 3.15.2 (I'm still working on getting current), openapi schema generation started failing with infinite recursion errors.

Re-reading the QSS docs, I discover I need to specify model when creating the QuerySetSequence for some functionality to work. Changing the above to 

```python
    members = GM2MSerializerField(queryset=autocomplete.QuerySetSequence(User.objects.all(), Group.objects.all(), model=User))
```

Then starts failing with

```
  File "/home/brobert/.virtualenvs/myapp/lib64/python3.9/site-packages/rest_framework/fields.py", line 652, in <dictcomp>
    key: (copy.deepcopy(value, memo) if (key not in ('validators', 'regex')) else value)
  File "/usr/lib64/python3.9/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.9/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.9/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.9/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.9/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: __getstate__() missing 1 required positional argument: 'self'
```

reductor is a reference to `__reduce_ex__`. After a bit of digging, I followed the definition of `User.__reduce__`, which lead me to the the inherited `Model.__reduce__` from django's base `Model` class:

```python
    def __reduce__(self):
        data = self.__getstate__()
        data[DJANGO_VERSION_PICKLE_KEY] = django.__version__
        class_id = self._meta.app_label, self._meta.object_name
        return model_unpickle, (class_id,), data
```

Meanwhile in #88, QSS' `ProxyModel` had been changed to:

```python
class ProxyModel:
    """
    Wrapper for generating DoesNotExist exceptions without modifying
    the provided model. This is needed by DRF as the views only handle
    the specific exception by the model.
    """

    def __init__(self, model=None):
        self._model = model

        # Define DoesNotExist for abstract models.
        if self._model and not self._model._meta.abstract:
            self.DoesNotExist = model.DoesNotExist
        else:
            self.DoesNotExist = ObjectDoesNotExist

    def __getattr__(self, name):
        return getattr(self._model, name)
```

Long story short, this code assumes __getattr__ will only ever be called to get DoesNotExist, and that it's safe to proxy calls for __getattr__ on an _instance_ to the _class_. I don't fully understand what DRF is doing such that I end up with __getattr__ invoked on the ProxyModel instance, but it appears to have gone wrong because __getattr__ was expecting to be called on an instance of User and actually got invoked on the User class itself.

From the context of #88 I think this `__getattr__` override exists solely to return a valid `DoesNotExist` exception object. In which case a quick hack of the following resolves the crashes:

```python
    def __getattr__(self, name):
        if name == 'DoesNotExist':
            return getattr(self._model, name)
        return super().__getattr__(self, name)
```

This proxies the request for the DoesNotExist object to the model, and relies on the default behaviour for anything else.

I'm not sure if this is the right thing to do in all cases; can someone more familiar with this codebase than me sanity check?

### PR DESCRIPTION
**Pull request by optiz0r**
ProxyModel.__getattr__ previously proxied all attribute lookups to the model class, but some third party libraries (e.g. DRF) will make calls which should be handled by the ProxyModel instance rather than the proxied class. For example, deepcopy invokes `__reduce_ex__()` that pickles an instance and needs access to `__getstate__()` which does note exist on a class.

Proxying calls to the model is required in some cases, e.g. for access to _meta.

This change avoids proxying any special methods (those starting with `__`) to the model. Fixes DRF schema generation for a serializer which contains a field using QuerySetSequence.

Adds test cases to verify behaviour of method proxying.

Fixes #107

### CODE REVIEW

File: queryset_sequence/__init__.py [hunk 1]
```diff
@@ -493,7 +493,11 @@ def __init__(self, model=None):
             self.DoesNotExist = ObjectDoesNotExist
 
     def __getattr__(self, name):
-        return getattr(self._model, name)
+        if name == "_meta":
+            return getattr(self._model, name)
+        if hasattr(super(), "__getattr__"):
+            return super().__getattr__(name)
+        raise AttributeError(name)
```
Comment (clokep) [inline queryset_sequence/__init__.py:500]: So with this change the *only* thing being proxied is `_meta`. Would it make more sense to define only that?

```python
@property
def _meta(self):
    return getattr(self._model, "_meta")
```

**Comment by clokep** [comment]
> Fixes DRF schema generation for a serializer which contains a field using QuerySetSequence.

Should there be a test for this and not just the proxy model tests?
